-- MySQL Script generated by MySQL Workbench
-- Sun Mar  4 11:52:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sopra-ws1718-team2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sopra-ws1718-team2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sopra-ws1718-team2` DEFAULT CHARACTER SET utf8 ;
USE `sopra-ws1718-team2` ;

-- -----------------------------------------------------
-- Table `sopra-ws1718-team2`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sopra-ws1718-team2`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `coins` INT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-ws1718-team2`.`Century`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sopra-ws1718-team2`.`Century` (
  `idCentury` INT NOT NULL AUTO_INCREMENT,
  `endTime` INT NOT NULL,
  `beginTime` INT NOT NULL,
  PRIMARY KEY (`idCentury`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-ws1718-team2`.`Quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sopra-ws1718-team2`.`Quiz` (
  `idQuiz` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `idCentury` INT NOT NULL,
  PRIMARY KEY (`idQuiz`, `idCentury`),
  INDEX `fk_Quiz_Level1_idx` (`idCentury` ASC),
  CONSTRAINT `fk_Quiz_Level1`
    FOREIGN KEY (`idCentury`)
    REFERENCES `sopra-ws1718-team2`.`Century` (`idCentury`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-ws1718-team2`.`MultipleChoiceQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sopra-ws1718-team2`.`MultipleChoiceQuestion` (
  `idQuestion` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  `answer1` VARCHAR(255) NOT NULL,
  `answer2` VARCHAR(255) NOT NULL,
  `answer3` VARCHAR(255) NOT NULL,
  `answer4` VARCHAR(255) NOT NULL,
  `correctAnswer` TINYINT(1) NOT NULL,
  `idQuiz` INT NOT NULL,
  PRIMARY KEY (`idQuestion`, `idQuiz`),
  INDEX `fk_Question_Quiz1_idx` (`idQuiz` ASC),
  CONSTRAINT `fk_Question_Quiz1`
    FOREIGN KEY (`idQuiz`)
    REFERENCES `sopra-ws1718-team2`.`Quiz` (`idQuiz`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-ws1718-team2`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sopra-ws1718-team2`.`Location` (
  `idLocation` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `backgroundPath` VARCHAR(255) NOT NULL,
  `idCentury` INT NOT NULL,
  PRIMARY KEY (`idLocation`, `idCentury`),
  INDEX `fk_Location_Century1_idx` (`idCentury` ASC),
  CONSTRAINT `fk_Location_Century1`
    FOREIGN KEY (`idCentury`)
    REFERENCES `sopra-ws1718-team2`.`Century` (`idCentury`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-ws1718-team2`.`Information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sopra-ws1718-team2`.`Information` (
  `idInformation` INT NOT NULL,
  `content` VARCHAR(5000) NULL,
  `isCoin` TINYINT(1) NULL,
  `idLocation` INT NOT NULL,
  PRIMARY KEY (`idInformation`, `idLocation`),
  INDEX `fk_Information_Location1_idx` (`idLocation` ASC),
  CONSTRAINT `fk_Information_Location1`
    FOREIGN KEY (`idLocation`)
    REFERENCES `sopra-ws1718-team2`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-ws1718-team2`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sopra-ws1718-team2`.`Messages` (
  `idMessages` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(1000) NULL,
  `seen` TINYINT NULL,
  `idReceiver` INT NOT NULL,
  `idSender` INT NOT NULL,
  PRIMARY KEY (`idMessages`, `idReceiver`, `idSender`),
  INDEX `fk_Messages_User1_idx` (`idReceiver` ASC),
  INDEX `fk_Messages_User2_idx` (`idSender` ASC),
  CONSTRAINT `fk_Messages_User1`
    FOREIGN KEY (`idReceiver`)
    REFERENCES `sopra-ws1718-team2`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_User2`
    FOREIGN KEY (`idSender`)
    REFERENCES `sopra-ws1718-team2`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-ws1718-team2`.`User_has_Century`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sopra-ws1718-team2`.`User_has_Century` (
  `idUser` INT NOT NULL,
  `idCentury` INT NOT NULL,
  `playedMemory` TINYINT(1) NULL,
  PRIMARY KEY (`idUser`, `idCentury`),
  INDEX `fk_User_has_Century_Century1_idx` (`idCentury` ASC),
  INDEX `fk_User_has_Century_User1_idx` (`idUser` ASC),
  CONSTRAINT `fk_User_has_Century_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `sopra-ws1718-team2`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Century_Century1`
    FOREIGN KEY (`idCentury`)
    REFERENCES `sopra-ws1718-team2`.`Century` (`idCentury`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-ws1718-team2`.`Friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sopra-ws1718-team2`.`Friend` (
  `idFriend` INT NOT NULL,
  `idUser` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idFriend`, `idUser`),
  INDEX `friend_id_idx` (`idFriend` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`idUser`)
    REFERENCES `sopra-ws1718-team2`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `friend_id`
    FOREIGN KEY (`idFriend`)
    REFERENCES `sopra-ws1718-team2`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-ws1718-team2`.`User_has_Quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sopra-ws1718-team2`.`User_has_Quiz` (
  `idUser` INT NOT NULL,
  `idQuiz` INT NOT NULL,
  `solved` DECIMAL NULL,
  PRIMARY KEY (`idUser`, `idQuiz`),
  INDEX `fk_User_has_Quiz_Quiz1_idx` (`idQuiz` ASC),
  INDEX `fk_User_has_Quiz_User1_idx` (`idUser` ASC),
  CONSTRAINT `fk_User_has_Quiz_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `sopra-ws1718-team2`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Quiz_Quiz1`
    FOREIGN KEY (`idQuiz`)
    REFERENCES `sopra-ws1718-team2`.`Quiz` (`idQuiz`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-ws1718-team2`.`User_has_Information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sopra-ws1718-team2`.`User_has_Information` (
  `idUser` INT NOT NULL,
  `idInformation` INT NOT NULL,
  `collectedCoin` TINYINT(1) NULL,
  PRIMARY KEY (`idUser`, `idInformation`),
  INDEX `fk_User_has_Information_Information1_idx` (`idInformation` ASC),
  INDEX `fk_User_has_Information_User1_idx` (`idUser` ASC),
  CONSTRAINT `fk_User_has_Information_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `sopra-ws1718-team2`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Information_Information1`
    FOREIGN KEY (`idInformation`)
    REFERENCES `sopra-ws1718-team2`.`Information` (`idInformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-ws1718-team2`.`User_has_MultipleChoiceQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sopra-ws1718-team2`.`User_has_MultipleChoiceQuestion` (
  `idUser` INT NOT NULL,
  `idQuestion` INT NOT NULL,
  `selectedAnswer` TINYINT(1) NOT NULL,
  `usedCard` TINYINT(1) NULL,
  PRIMARY KEY (`idUser`, `idQuestion`),
  INDEX `fk_User_has_MultipleChoiceQuestion_MultipleChoiceQuestion1_idx` (`idQuestion` ASC),
  INDEX `fk_User_has_MultipleChoiceQuestion_User1_idx` (`idUser` ASC),
  CONSTRAINT `fk_User_has_MultipleChoiceQuestion_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `sopra-ws1718-team2`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_MultipleChoiceQuestion_MultipleChoiceQuestion1`
    FOREIGN KEY (`idQuestion`)
    REFERENCES `sopra-ws1718-team2`.`MultipleChoiceQuestion` (`idQuestion`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-ws1718-team2`.`MemoryData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sopra-ws1718-team2`.`MemoryData` (
  `idMemoryData` INT NOT NULL,
  `idCentury` INT NOT NULL,
  `card1` VARCHAR(45) NULL,
  `card2` VARCHAR(45) NULL,
  PRIMARY KEY (`idMemoryData`, `idCentury`),
  INDEX `fk_Memory_Century1_idx` (`idCentury` ASC),
  CONSTRAINT `fk_Memory_Century1`
    FOREIGN KEY (`idCentury`)
    REFERENCES `sopra-ws1718-team2`.`Century` (`idCentury`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-ws1718-team2`.`Cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sopra-ws1718-team2`.`Cards` (
  `idCards` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('FOOL', 'JUDGEMENT', 'WHEEL_OF_FORTUNE') NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idCards`, `idUser`),
  INDEX `fk_Cards_User1_idx` (`idUser` ASC),
  CONSTRAINT `fk_Cards_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `sopra-ws1718-team2`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
